{{ config(materialized='incremental') }}

with source_data3 as (
select distinct BUMP,CROSSING,_MODIFIED,GIVE_WAY,JUNCTION,AMENITY,NO_EXIT,RAILWAY,ROUNDABOUT,STATION,STOP,
TRAFFIC_CALMING,TRAFFIC_SIGNAL,TURNING_LOOP from {{source('DEVELOPER_DB','STAGE_US_DATA')}}
),
second_data3 as (
select  concat('A-', cast(seq_resn.nextval as varchar)) as R_ID,AMENITY,
BUMP,CROSSING,GIVE_WAY,JUNCTION,NO_EXIT,RAILWAY,ROUNDABOUT,STATION,STOP,TRAFFIC_CALMING,TRAFFIC_SIGNAL,TURNING_LOOP ,_MODIFIED
 as LOAD_TIME from source_data3
)

select  R_ID,
BUMP,CROSSING,GIVE_WAY,JUNCTION,NO_EXIT,AMENITY,RAILWAY,ROUNDABOUT,STATION,STOP,TRAFFIC_CALMING,
TRAFFIC_SIGNAL,TURNING_LOOP, LOAD_TIME from second_data3